site_name: Data Processing Handbook - DCAN Labs
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - Slurm: slurm.md
  - Interactive High Performance Computing (HPC) Resources: hpc.md
  - MSI Partitions: partitions.md
  - Slurm Parameters: slurm-params.md
  - fairshare: fairshare.md
  - MSI Module System: modules.md
  - Miniconda Environments: miniconda.md
  - Virtual Machine: vm.md
  - DICOM to BIDS conversion: dcm2bids.md
  - NORDIC Denoising and BIDS NORDIC Wrapper: nordic.md
  - BIDS Validation: bids.md
  - Storage Allocation Estimates: storage.md
  - S3: s3.md
  - Optimizing sbatch Parameters: optimizing.md
  - Pipelines: pipelines.md
  - S3 Pipeline Wrappers: wrappers.md
  - file-mapper: filemapper.md
  - Precision Mapping Wrapper: precision.md
  - Job Submissions: jobs.md
  - Containers: containers.md
  - Processing Status: status.md
  - Troubleshooting and Image Viewing: troubleshooting.md
  - Fast Track QC Comparison (ABCD): fasttrack.md
  - Data Uploads and Transfer: uploads.md
  - Common MSI Roadblocks: roadblocks.md
  - Testing CABINET: cabinet-testing.md
  - Requests and Questions: requests.md