site_name: Data Processing Handbook - DCAN Labs
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - Using MSI: 
      - Interactive High Performance Computing (HPC) Resources: hpc.md
      - MSI Partitions: partitions.md
      - MSI Module System: modules.md
      - First Login Steps: msi-login.md
      - Storage Allocation Estimates: storage.md
      - S3: s3.md
      - Common MSI Roadblocks: roadblocks.md
  - Slurm/Processing Jobs:
      - Slurm: slurm.md
      - Slurm Parameters: slurm-params.md
      - Optimizing sbatch Parameters: optimizing.md
      - Job Submissions: jobs.md
      - fairshare: fairshare.md
  - Setting up Coding Environments:
      - VS Code: vscode.md 
      - Miniconda Environments: miniconda.md
      - Best Coding Practices: workflow.md
  - BIDS:
      - DICOM to BIDS conversion: dcm2bids.md
      - BIDS Validation: bids.md
      - NORDIC Denoising and BIDS NORDIC Wrapper: nordic.md
  - Preprocessing:
      - Preprocessing: preprocessing.md
  - Processing:
      - Pipelines: pipelines.md
      - S3 Pipeline Wrappers: wrappers.md
  - Postprocessing:
      - file-mapper: filemapper.md    
      - Precision Mapping Wrapper: precision.md
      - Processing Status: status.md
      - How to Transfer ABCC Data to the NGDR: ngdr-transfer.md
  - Troubleshooting:
      - Troubleshooting and Image Viewing: troubleshooting.md
      - Testing CABINET: cabinet-testing.md
  - Virtual Machine: vm.md
  - Containers: containers.md
  - Fast Track QC Comparison (ABCD): fasttrack.md
  - Data Uploads and Transfer: uploads.md
  - Requests and Questions: requests.md
  - Contributors and Papers: contributions.md
