site_name: DCAN Labs Informational Guide
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - Using MSI: 
      - Interactive High Performance Computing (HPC) Resources: hpc.md
      - MSI Partitions: partitions.md
      - MSI Module System: modules.md
      - First Login Steps: msi-login.md
      - Data Storage/Tracking: storage.md
      - S3: s3.md
      - Common MSI Roadblocks: roadblocks.md
  - SLURM Jobs:
      - Slurm Commands: slurm.md
      - Slurm Jobs: slurm-params.md
      - Optimizing sbatch Parameters: optimizing.md
      - Job Submissions: jobs.md
      - fairshare: fairshare.md
      - Queue Optimization: queue-optimization.md
      - Analyzing Motion Regressors: motion-regressor.md
  - Software Environments:
      - VS Code: vscode.md 
      - Miniconda Environments: miniconda.md
      - Best Coding Practices: workflow.md
      - Software Versioning: versioning.md
      - Containers: containers.md
      - Virtual Machine: vm.md
  - Coding Standards:
      - Best Practices: coding-practices.md
  - GitHub:
      - GitHub Tips and Tricks: github-tips.md
      - GitHub History Scrub: github-scrub.md
  - BIDS:
      - DICOM to BIDS conversion: dcm2bids.md
      - BIDS Validation: bids.md
      - NORDIC Denoising and BIDS NORDIC Wrapper: nordic.md
  - Before processing:
      - Defacing: infant-preproc.md
      - 10.5T NHP ABCD BIDS Pipeline Synth: preprocessing.md
      - Fast Track QC Comparison (ABCD): fasttrack.md
  - Processing:
      - Pipelines: pipelines.md
      - S3 Pipeline Wrappers: wrappers.md
      - Infant Pipeline Documentation: infant-doc.md
      - Best Practices: processing-sop.md
  - After processing:
      - file-mapper: filemapper.md    
      - Precision Mapping Wrapper: precision.md
      - Processing Status: status.md
      - Infant Quality Assessment: infant-qa.md
  - Troubleshooting:
      - Troubleshooting and Image Viewing: troubleshooting.md
      - Testing BIBSnet: bibsnet-testing.md
      - Requests and Questions: requests.md
  - Quality Control:
      - BrainSwipes: brainswipes.md
      - Infant Data: infant-qc.md
  - Data Uploads and Transfers:
      - Data Transfers: uploads.md
      - Transfer ABCC Data to the NGDR: ngdr-transfer.md
      - Collections on the NDA: nda.md
      - Request to Archive Data on the NDA: nda-archive.md
  - Lab Resources:
      - Basecamp: basecamp.md
      - Recorded Presentations: presentations.md
      - UMN Recommended Courses: courses.md
  - PHI:
      - "Protected Health Information (PHI): A Quick Guide": phi-quick-guide.md
  - Contributions:
      - Contributors and Papers: contributions.md
  - THANK YOU FOR USING THE DPH:
      - _____: blank.md
