site_name: CDNI's Brain
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: 
      - Table of Contents: index.md
      - About: about.md
  - MSI: 
      - Getting Started: msi-login.md
      - Tier 1 (High-Performance Computing) Resources: hpc.md
      - Partitions: partitions.md
      - Module System: modules.md
      - Data Storage/Tracking: storage.md
      - Tier 2 (S3): s3.md
      - Tips & Tricks: roadblocks.md
  - SLURM:
      - Slurm Commands: slurm.md
      - Slurm Jobs: slurm-params.md
      - Cronjobs: scron.md
      - Resource Optimization: optimizing.md
  - Software:
      - VS Code: vscode.md 
      - Miniconda Environments: miniconda.md
      - Software Versioning: versioning.md
      - Containers: containers.md
      - Virtual Machine: vm.md
  - Coding Standards:
      - Best Practices: coding-practices.md
  - GitHub:
      - Beginner's Guide: github-quick-guide.md
      - Common Git Commands: git-commands.md
      - Tips and Tricks: github-tips.md
      - History Scrub: github-scrub.md
  - BIDS:
      - DICOM to BIDS conversion: dcm2bids.md
      - BIDS Validation: bids.md
      - BIDS Directory Structure: bids-directory-structure.md
  - Before processing:
      - NORDIC Denoising: nordic.md
      - Infant Preprocessing QA: infant-preproc.md
      - MRI Image De-Identification: deidentification.md
      - Preparing for NHP Processing: preprocessing.md
      - Fast Track QC Comparison (ABCD): fasttrack.md
      - Respiration Rate Settings: resp-rate.md
  - Processing:
      - Pipelines: pipelines.md
      - S3 Pipeline Wrappers: wrappers.md
      - Infant Pipeline Documentation: infant-doc.md
      - DCAN-infant Templates/Atlases: dcan-infant-templates.md
      - Running nnUNet Predict: nnunet.md
      - Best Practices: processing-sop.md
  - After processing:
      - file-mapper: filemapper.md    
      - Precision Mapping Wrapper: precision.md
      - Processing Status: status.md
      - Error Query: error_query.md
      - Infant Quality Assessment: infant-qa.md
      - Analyzing Motion Regressors: motion-regressor.md
  - Troubleshooting:
      - Troubleshooting Pipelines: troubleshooting.md
      - Testing BIBSnet: bibsnet-testing.md
      - Requests and Questions: requests.md
  - Quality Control:
      - BrainSwipes: brainswipes.md
  - Data Uploads and Transfers:
      - Data Transfers: uploads.md
  - Segmentation Model:
        - Model Training: training-nnunet.md
  - Lab Resources:
      - Basecamp: basecamp.md
      - Recorded Presentations: presentations.md
      - UMN Recommended Courses: courses.md
      - UMN Computer Installs: installs.md
      - ZENODO: zenodo.md
      - A Quick Guide on Protected Health Information (PHI): phi-quick-guide.md
  - Plotting Tools:
      - Figure Maker: figure-maker.md
      - Connectivity Matrices: matrices.md
      - Skinny Plot: skinny-plot.md
  - Analysis Tools:
      - Cifti Conn Matrix: cifti-matrix.md
      - Seed Map Parcellation Wrapper: seed-map.md
      - Template Matching: template-matching.md
      - F Conn Regression: f-conn.md
      - BWAS: bwas.md
      - Calculating Rest Minutes Pre- and Post-Motion Correction: rest_minutes_motion_correction_calculation.md
  - MR Image:
      - MR-Image-Translation: mr-image-translation.md
  - Contributions:
      - Contributors and Papers: contributions.md
  - THANK YOU FOR USING THE BRAIN:
      - _____: blank.md
